baseURL: "/"
title: QCBS R Workshop Series
theme: airspace-hugo
paginate: '4'
summaryLength: '30'
disableLanguages: [it, de]
disqusShortname: ''
googleAnalytics: 'UA-200956415-1'
outputs:
  home: HTML
markup:
  goldmark:
    renderer:
      unsafe: yes
  tableOfContents:
    endLevel: 6
    ordered: no
    startLevel: 2
params:
  author: QCBS R Workshop Series
  contact:
    address_descriptors: no
    email: qcbs.csbq.r@gmail.com
    form:
      action: '#'
      enable: yes
      success_image: images/paper-plane.svg
      use_netlify: yes
    location: "\r\n**QCBS R Workshop Series**  \r\nQuébec  \r\nCanada"
    phone: no
  cookies:
    enable: yes
    expire_days: 2
  counter:
    enable: yes
    username: ''
  description: This is meta description
  gmap:
    enable: yes
    gmap_api: AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU
    map_latitude: '45.50676408098079'
    map_longitude: '-73.59668255645155'
    map_marker: images/marker.png
  image: images/qcbs_logo_image0032.png
  logo: images/qcbs_logo_image0032.png
  logo_width: 90px
  plugins:
    css:
      - attributes: media='screen'
        link: plugins/bootstrap/css/bootstrap.min.css
      - attributes: ''
        link: plugins/ionicons/css/ionicons.min.css
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.css
      - attributes: ''
        link: plugins/slick/slick.css
    js:
      - attributes: ''
        link: plugins/jquery/jquery.min.js
      - attributes: ''
        link: plugins/bootstrap/js/bootstrap.min.js
      - attributes: ''
        link: plugins/slick/slick.min.js
      - attributes: ''
        link: plugins/magnific-popup/magnific-popup.min.js
      - attributes: ''
        link: plugins/shuffle/shuffle.min.js
      - attributes: defer
        link: plugins/google-map/gmap.js
  preloader:
    enable: yes
    preloader: ''
  social:
    - icon: ion-social-googleplus-outline
      link: '#'
    - icon: ion-social-github-outline
      link: 'github.com/QCBSRworkshops/'
    - icon: ion-social-twitter-outline
      link: '#'
    - icon: ion-social-facebook-outline
      link: '#'
  widgets:
    sidebar:
      - recent_posts
      - taxonomy_category
      - taxonomy_tags
languages:
  de:
    contentDir: content/german
    copyright: Copyright &copy; 2021 [QCBS R Workshop Series](https://themefisher.com). Alle
      Rechte vorbehalten.
    languageCode: de-DE
    languageName: Deutsch
    menu:
      footer:
        - URL: about
          name: Über
          weight: 1
        - URL: project
          name: Projekt
          weight: 2
        - URL: service
          name: Dienstleistung
          weight: 3
        - URL: pricing
          name: Preise
          weight: 4
        - URL: faq
          name: Häufige Fragen
          weight: 5
        - URL: contact
          name: Kontakt
          weight: 6
      main:
        - hasChildren: yes
          name: Mehr
          weight: 5
    weight: 3
  en:
    contentDir: content/english
    copyright: Copyright &copy; 2021 [QCBS R Workshop Series](qcbsrworkshops.github.io/website). All Rights
      Reserved.
    languageCode: en-US
    languageName: English
    menu:
      footer:
        - URL: about
          name: About
          weight: 1
        - URL: workshops
          name: Workshops
          weight: 2
        - URL: symposium
          name: R Symposium
          weight: 3
        - URL: contributing
          name: Contribute
          weight: 4
        - URL: pricing
          name: Registration
          weight: 5
        - URL: faq
          name: FAQ
          weight: 6
        - URL: contact
          name: Contact
          weight: 7
      main:
        - hasChildren: yes
          name: More
          weight: 6
    weight: 1
  fr:
    contentDir: content/french
    copyright: Copyright &copy; 2021 [QCBS R Workshop Series](qcbsrworkshops.github.io/website). Tous
      droits réservés.
    languageCode: fr-FR
    languageName: Français
    menu:
      footer:
        - URL: about
          name: À propos
          weight: 1
        - URL: project
          name: Projet
          weight: 2
        - URL: service
          name: Service
          weight: 3
        - URL: pricing
          name: Tarification
          weight: 4
        - URL: faq
          name: Questions fréquentes
          weight: 5
        - URL: contact
          name: Contact
          weight: 6
      main:
        - hasChildren: yes
          name: Plus
          weight: 5
    weight: 2
  it:
    contentDir: content/italian
    copyright: Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tutti
      i diritti riservati.
    languageCode: it-IT
    languageName: Italiano
    menu:
      footer:
        - URL: about
          name: Chi siamo
          weight: 1
        - URL: project
          name: Progetto
          weight: 2
        - URL: service
          name: Servizio
          weight: 3
        - URL: pricing
          name: Tariffazione
          weight: 4
        - URL: faq
          name: Domande frequenti
          weight: 5
        - URL: contact
          name: Contatta
          weight: 6
      main:
        - hasChildren: yes
          name: Più
          weight: 5
    weight: 2
