################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "http://examplesite.org"
title = "Airspace | Creative Agency Hugo Template"
theme = "airspace-hugo"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = []
# Short name to enable Disqus comments
disqusShortname = "" # Get your shortname from here: https://disqus.com/profile/signup/
# Measurement ID (G-XXXXXXX) to enable Google Analytics
googleAnalytics = ""


################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]


################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false


################################# Default parameters ##########################
[params]
logo = "images/logo.png"
logo_width = "150px"
# OpenGraph / Twitter Card metadata
description = "This is meta description"
author = "Themefisher"
image = "images/logo.png" # this image will be used as fallback if a page has no image of its own


################################# Sidebar widgets #############################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


################################# Contact page ################################
[params.contact]
# Address block
phone = "0124857985320"
email = "demo@email.com"
location = """
**Themefisher**  
North Main Street  
Brooklyn, New South Wales  
Australia
"""
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = false
[params.contact.form]
enable = true
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = true
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "#"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"


################################# Google map ##################################
[params.gmap]
enable = true
gmap_api = "AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


################################# Preloader ###################################
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif image


################################# Cookies #####################################
[params.cookies]
enable = true
expire_days = 2


################################# counter.dev analytics #######################
# This is a [privacy-friendly alternative](https://counter.dev/privacy.html) to Google Analytics & Co.
[params.counter]
enable = true
# counter.dev username, see https://counter.dev/setup.html
username = ""


################################# Social Media ################################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################# Plugins #####################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


################################# English translation #########################
[languages.en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). All Rights Reserved."

# Main menu
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.en.menu.main]]
hasChildren = true
name = "More"
weight = 5

# Footer menu
[[languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[languages.en.menu.footer]]
name = "Project"
URL = "project"
weight = 2

[[languages.en.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[languages.en.menu.footer]]
name = "Pricing"
URL = "pricing"
weight = 4

[[languages.en.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6


################################# French translation ##########################
[languages.fr]
languageName = "Français"
languageCode = "fr-FR"
contentDir = "content/french"
weight = 2
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tous droits réservés."

# Main menu
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.fr.menu.main]]
hasChildren = true
weight = 5
name = "Plus"

# Footer menu
[[languages.fr.menu.footer]]
name = "À propos"
URL = "about"
weight = 1

[[languages.fr.menu.footer]]
name = "Projet"
URL = "project"
weight = 2

[[languages.fr.menu.footer]]
name = "Service"
URL = "service"
weight = 3

[[languages.fr.menu.footer]]
name = "Tarification"
URL = "pricing"
weight = 4

[[languages.fr.menu.footer]]
name = "Questions fréquentes"
URL = "faq"
weight = 5

[[languages.fr.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6


################################# Italian translation ##########################
[languages.it]
languageName = "Italiano"
languageCode = "it-IT"
contentDir = "content/italian"
weight = 2
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Tutti i diritti riservati."

# Main menu
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.it.menu.main]]
hasChildren = true
weight = 5
name = "Più"

# Footer menu
[[languages.it.menu.footer]]
name = "Chi siamo"
URL = "about"
weight = 1

[[languages.it.menu.footer]]
name = "Progetto"
URL = "project"
weight = 2

[[languages.it.menu.footer]]
name = "Servizio"
URL = "service"
weight = 3

[[languages.it.menu.footer]]
name = "Tariffazione"
URL = "pricing"
weight = 4

[[languages.it.menu.footer]]
name = "Domande frequenti"
URL = "faq"
weight = 5

[[languages.it.menu.footer]]
name = "Contatta"
URL = "contact"
weight = 6


################################# German translation ##########################
[languages.de]
languageName = "Deutsch"
languageCode = "de-DE"
contentDir = "content/german"
weight = 3
copyright = "Copyright &copy; 2021 [Themefisher](https://themefisher.com). Alle Rechte vorbehalten."

# Main menu
# NOTE: Leaf entries linking to content should be defined in the content file's respective front matter.
[[languages.de.menu.main]]
hasChildren = true
name = "Mehr"
weight = 5

# Footer menu
[[languages.de.menu.footer]]
name = "Über"
URL = "about"
weight = 1

[[languages.de.menu.footer]]
name = "Projekt"
URL = "project"
weight = 2

[[languages.de.menu.footer]]
name = "Dienstleistung"
URL = "service"
weight = 3

[[languages.de.menu.footer]]
name = "Preise"
URL = "pricing"
weight = 4

[[languages.de.menu.footer]]
name = "Häufige Fragen"
URL = "faq"
weight = 5

[[languages.de.menu.footer]]
name = "Kontakt"
URL = "contact"
weight = 6
